name: Nightly Playwright Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  Run_Test:
    timeout-minutes: 90
    name: ğŸ§ª Running E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: currentDate
        run: |
          echo "date=$(date +'%Y-%m-%d %H-%M')" >> $GITHUB_OUTPUT
      #    
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      #
      - name: ğŸ“¦ Install dependencies
        run: npm install
      #  
      - name: ğŸ–¥ï¸ Install Playwright Browsers
        run: npx playwright install
      #  
      - name: ğŸ§¾ Run Playwright tests
        run: npx playwright test
      #    
      - name: ğŸ“¤ Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
          
  Generate_Allure_Report:
    name: ğŸ“Š Generate and Publish Allure Report
    runs-on: ubuntu-latest
    needs: Run_Test
    if: always()
    
    steps:
      - name: â¬‡ï¸ Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      #
      - name: ğŸ“œ Checkout gh-pages (Allure history source)
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1
      #
      - name: ğŸ§¹ Clean .git from gh-pages checkout
        if: always()
        run: rm -rf gh-pages/.git || true
      #  
      - name: ğŸ“ Restore Allure History # gh-pages â”€â”€â–º allure-history â”€â”€â–º allure-report â”€â”€â–º gh-pages
        if: always()
        run: |
          mkdir -p allure-history
          cp -R gh-pages/. allure-history/ || true
        #
      - name: ğŸ“Š Generate Allure Report with History
        uses: simple-elf/allure-report-action@latest
        id: allure-report
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          allure_report: allure-report
          keep_reports: 15
      #
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report' # The folder generated by Allure

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        #
        
      - name: ğŸ“¤ Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      #
