name: Nightly Playwright Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write
  pages: write
  id-token: write

jobs:
  Run_Test:
    timeout-minutes: 90
    name: ğŸ§ª Running E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: currentDate
        run: |
          echo "date=$(date +'%Y-%m-%d %H-%M')" >> $GITHUB_OUTPUT
      #    
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      #
      - name: ğŸ“¦ Install dependencies
        run: npm install
      #  
      - name: ğŸ–¥ï¸ Install Playwright Browsers
        run: npx playwright install
      #  
      - name: ğŸ§¾ Run Playwright tests
        run: npx playwright test
      #    
      - name: ğŸ“¤ Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
      #    
      - name: ğŸ” Inspect Allure Report folder
        run: |
          echo "ğŸ“ Contents of allure-report:"
          ls -la allure-report
          echo "ğŸ“¦ Size:"
          du -sh allure-report    
      #
      - name: ğŸ” Inspect Allure Results folder
        run: |
          echo "ğŸ“ Contents of allure-resuts:"
          ls -la ./allure-results
          echo "ğŸ“¦ Size:"
          du -sh allure-results  
          
  Generate_Allure_Report:
    name: ğŸ“Š Generate and Publish Allure Report
    runs-on: ubuntu-latest
    needs: Run_Test
    if: always()
    
    steps:
      - name: â¬‡ï¸ Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      #
      - name: ğŸ“œ Checkout gh-pages (Allure history source) # Checkout the gh-pages branch to retrieve the historical artifacts from Allure.
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1
          lfs: true
      #
      - name: ğŸ“ Restore Allure History
        run: |
          mkdir -p allure-history
          if [ -d "gh-pages/allure-history" ]; then
            echo "Restoring Allure history..."
            cp -R gh-pages/allure-history/. allure-history/
          fi
      #
      - name: ğŸ“Š Generate Allure Report with History
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 15
      #
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report' # The folder generated by Allure
          
      - name: ğŸ” Inspect Allure Report folder
        run: |
          echo "ğŸ“ Contents of allure-report:"
          ls -la ./allure-report
          echo "ğŸ“¦ Size:"
          du -sh allure-report    

      - name: ğŸ” Inspect Allure Results folder
        run: |
          echo "ğŸ“ Contents of allure-resuts:"
          ls -la ./allure-results
          echo "ğŸ“¦ Size:"
          du -sh allure-results    

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        #
