name: Nightly Playwright Tests - Full History

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write
  pages: write
  id-token: write

jobs:
  Run_Test:
    timeout-minutes: 90
    name: ğŸ§ª Running E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: currentDate
        run: |
          echo "date=$(date +'%Y-%m-%d %H-%M')" >> $GITHUB_OUTPUT
      #    
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      #
      - name: ğŸ“¦ Install dependencies
        run: npm install
      #  
      - name: ğŸ–¥ï¸ Install Playwright Browsers
        run: npx playwright install
      #  
      - name: ğŸ§¾ Run Playwright tests
        run: npx playwright test
      #    
      - name: ğŸ“¤ Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 5
          
  Generate_and_Deploy_Report:
    name: ğŸ“Š Report Generation & Deploy
    runs-on: ubuntu-latest
    needs: Run_Test
    if: always()
    
    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: â¬‡ï¸ Download Current Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      #    
      - name: ğŸ“œ Download Previous Allure History
        id: download_history
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          workflow: playwright_full_history.yml
          workflow_conclusion: completed
          name: history-artifact
          path: allure-history
          search_artifacts: true
          if_no_artifact_found: warn
      #    
      - name: ğŸ“ Copy allure-history to gh-pages folder # Allure-history is from artifacts
        # if [ -d "previous-history" ] && [ "$(ls -A previous-history)" ]; then 
        run: |
          mkdir -p gh-pages
          if [ -d "gh-pages" ] && [ -d "allure-history" ]; then
            cp -r allure-history/. gh-pages/
          fi
    #
      - name: ğŸ” Inspect Root Folder
        run: |
          echo "ğŸ“ Contents of root:"
          ls -la   
    #
      - name: ğŸ” Inspect allure-history folder
        run: |
          echo "ğŸ“ Contents of allure-history folder:"
          if [ -d "allure-history" ]; then
            ls -la ./allure-history
          fi  
    #
      - name: ğŸ” Inspect allure-history/last-history folder
        run: |
          echo "ğŸ“ Contents of allure-history/last-history folder:"
          if [ -d "allure-history/last-history" ]; then
            ls -la ./allure-history/last-history
          fi   
    #
      - name: ğŸ” Inspect gh-pages folder
        run: |
          echo "ğŸ“ Contents of gh-pages folder:"
          if [ -d "gh-pages" ]; then
            ls -la ./gh-pages
          fi  
      #
      - name: ğŸ” Inspect gh-pages/last-history folder
        run: |
          echo "ğŸ“ Contents of gh-pages/last-history folder:"
          if [ -d "gh-pages/last-history" ]; then
            ls -la ./gh-pages/last-history
          fi  
    #      
      - name: ğŸ“Š Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 5
     #     
      - name: ğŸ’¾ Save History for Next Run
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: history-artifact
          path: allure-history
          retention-days: 5
    #
      - name: ğŸ—ï¸ Setup Pages
        uses: actions/configure-pages@v4
    #
      - name: ğŸ“¤ Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
    #
      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
     # 
      - name: ğŸ” Inspect Root Folder
        run: |
          echo "ğŸ“ Contents of root"
          ls -la   
      #
      - name: ğŸ” Inspect Allure Results folder
        run: |
          echo "ğŸ“ Contents of allure-resuts:"
          ls -la ./allure-results
      #    
      - name: ğŸ” Inspect Allure Results/history folder
        run: |
          echo "ğŸ“ Contents of allure-resuts/history:"
          ls -la ./allure-results/history
      #    
      - name: ğŸ” Inspect Allure Report folder
        run: |
          echo "ğŸ“ Contents of allure-report:"
          ls -la ./allure-report
      #    
      - name: ğŸ” Inspect Allure Report/history folder
        run: |
          echo "ğŸ“ Contents of allure-report/history:"
          ls -la ./allure-report/history
      #   
      - name: ğŸ” Inspect allure-history folder
        run: |
          echo "ğŸ“ Contents of allure-history folder:"
          ls -la ./allure-history
      #
      - name: ğŸ” Inspect allure-history/last-history folder
        run: |
          echo "ğŸ“ Contents of allure-history/last-history folder:"
          ls -la ./allure-history/last-history    
      #          
      - name: ğŸ” Inspect GH Pages Folder
        run: |
          echo "ğŸ“ Contents of GH Pages:"
          ls -la ./gh-pages
          echo "ğŸ“¦ Size:"
          du -sh allure-results 
      #   

         
     
