name: Nightly Playwright Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write
  pages: write
  id-token: write

jobs:
  Run_Test:
    timeout-minutes: 90
    name: ğŸ§ª Running E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: currentDate
        run: |
          echo "date=$(date +'%Y-%m-%d %H-%M')" >> $GITHUB_OUTPUT
      #    
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      #
      - name: ğŸ“¦ Install dependencies
        run: npm install
      #  
      - name: ğŸ–¥ï¸ Install Playwright Browsers
        run: npx playwright install
      #  
      - name: ğŸ§¾ Run Playwright tests
        run: npx playwright test
      #    
      - name: ğŸ“¤ Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 15

  Generate_Allure_Report:
    name: ğŸ“Š Generate and Publish Allure Report
    runs-on: ubuntu-latest
    needs: Run_Test
    if: always()
    
    steps:
      - name: â¬‡ï¸ Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      # 
      - name: ğŸ“ Restore Allure History
        run: |
          if [ -d "previous-report/history" ]; then
            mkdir -p allure-results/history
            cp -R previous-report/history/. allure-results/history/
            echo "âœ… Allure history restored"
          else
            echo "â„¹ï¸ No previous history found"
          fi
      #
      - name: ğŸ“Š Generate Allure Report with History
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
      #
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'allure-report' # The folder generated by Allure
      #    
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
     #     
      - name: ğŸ” Inspect Allure Report folder
        run: |
          echo "ğŸ“ Contents of allure-report:"
          ls -la ./allure-report
          echo "ğŸ“¦ Size:"
          du -sh allure-report    
      #
      - name: ğŸ” Inspect Allure Results folder
        run: |
          echo "ğŸ“ Contents of allure-resuts:"
          ls -la ./allure-results
          echo "ğŸ“¦ Size:"
          du -sh allure-results 
#
      - name: ğŸ” Inspect Allure History folder
        run: |
          echo "ğŸ“ Contents of allure-resuts:"
          ls -la ./allure-results/history
          echo "ğŸ“¦ Size:"
          du -sh allure-results 
      #   
      - name: ğŸ” Inspect Allure History folder
        run: |
          echo "ğŸ“ Contents of allure-history:"
          ls -la ./allure-history
          echo "ğŸ“¦ Size:"
          du -sh allure-history
    #     
      - name: ğŸ” Inspect Root Folder
        run: |
          echo "ğŸ“ Contents of root"
          ls -la   
      #
      - name: ğŸ” Inspect gh-pages Folder
        run: |
          echo "ğŸ“ Contents of root"
          ls -la ./gh-pages   
      #
      - name: ğŸ” Validate downloaded Allure history
        run: |
          if [ -d "previous-report/history" ]; then
            echo "âœ… Allure history found:"
            ls -la previous-report/history
          else
            echo "âš ï¸ No previous Allure history found (first run or reset)"
          fi

      - name: ğŸ” Validate downloaded Previous history
        run: |
          if [ -d "previous-report/history" ]; then
            echo "âœ… Allure history found:"
            ls -la previous-report
          else
            echo "âš ï¸ No previous Allure history found (first run or reset)"
          fi

          
