name: Nightly Playwright Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write
  pages: write
  id-token: write

jobs:
  Run_Test:
    timeout-minutes: 90
    name: ğŸ§ª Running E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: currentDate
        run: |
          echo "date=$(date +'%Y-%m-%d %H-%M')" >> $GITHUB_OUTPUT
      #    
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      #
      - name: ğŸ“¦ Install dependencies
        run: npm install
      #  
      - name: ğŸ–¥ï¸ Install Playwright Browsers
        run: npx playwright install
      #  
      - name: ğŸ§¾ Run Playwright tests
        run: npx playwright test
      #    
      - name: ğŸ“¤ Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 15
          
  Generate_and_Deploy_Report:
    name: ğŸ“Š Report Generation & Deploy
    runs-on: ubuntu-latest
    needs: Run_Test
    if: always()
    
    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: â¬‡ï¸ Download Current Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      #    
      - name: ğŸ” Inspect Root Folder
        run: |
          echo "ğŸ“ Contents of root"
          ls -la   
     #     
      - name: ğŸ” Get workflow ID
        id: get_workflow_id
        run: |
            WORKFLOW_NAME="Nightly Playwright Tests"
        
            WORKFLOW_ID=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows \
              | jq -r ".workflows[] | select(.name == \"${WORKFLOW_NAME}\") | .id")
        
            if [ -z "$WORKFLOW_ID" ] || [ "$WORKFLOW_ID" = "null" ]; then
              echo "âŒ Workflow ID not found"
              exit 1
            fi
        
            echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_OUTPUT
            echo "âœ… Workflow ID: $WORKFLOW_ID"
      #
          
      - name: ğŸ“œ Download Previous Allure History
        id: download_history
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          workflow: ${{ steps.get_workflow_id.outputs.workflow_id }}
          workflow_conclusion: completed
          name: history-artifact
          path: previous-history
          search_artifacts: true
          if_no_artifact_found: warn
      #    
      - name: ğŸ” Debug workflow & run
        if: always()
        run: |
          echo "Workflow ID used: ${{ steps.get_workflow_id.outputs.workflow_id }}"
          echo "Artifact found: ${{ steps.download_history.outputs.found_artifact }}"
          echo "Source run ID: ${{ steps.download_history.outputs.run_id }}"
          echo "Source run number: ${{ steps.download_history.outputs.run_number }}"
      #
      - name: ğŸ” List artifacts via GitHub API
        run: |
          curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
            | jq '.artifacts[] | {name, expired, created_at}'
      #
      - name: ğŸ“ Clean History
        run: |
          mkdir -p data-for-allure
          if [ -d "previous-history" ]; then
            cp -r previous-history/. data-for-allure/
          fi

      - name: ğŸ“Š Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: data-for-allure
          keep_reports: 15

      # Precisamos subir a pasta allure-history como artefato para a PRÃ“XIMA execuÃ§Ã£o
      - name: ğŸ’¾ Save History for Next Run
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: history-artifact
          path: data-for-allure
          retention-days: 30

      - name: ğŸ—ï¸ Setup Pages
        uses: actions/configure-pages@v4

      - name: ğŸ“¤ Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report # Pasta final gerada pela action

      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
     # 
      - name: ğŸ” Inspect Root Folder
        run: |
          echo "ğŸ“ Contents of root"
          ls -la   
      #
      - name: ğŸ” Inspect Allure Results folder
        run: |
          echo "ğŸ“ Contents of allure-resuts:"
          ls -la ./allure-results
          echo "ğŸ“¦ Size:"
          du -sh allure-results
      #    
      - name: ğŸ” Inspect Allure Report folder
        run: |
          echo "ğŸ“ Contents of allure-report:"
          ls -la ./allure-report
          echo "ğŸ“¦ Size:"
          du -sh allure-report    
      #
      - name: ğŸ” Inspect data-for-allure folder
        run: |
          echo "ğŸ“ Contents of allure Last History:"
          ls -la ./data-for-allure
      #
      - name: ğŸ” Inspect data-for-allure History folder
        run: |
          echo "ğŸ“ Contents of allure-history:"
          ls -la ./data-for-allure/last-history
          
      - name: ğŸ” Inspect GH Pages Folder
        run: |
          echo "ğŸ“ Contents of GH Pages:"
          ls -la ./gh-pages
          echo "ğŸ“¦ Size:"
          du -sh allure-results 
      #   

         
     
