name: Playwright Allure Reports

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  test:
    timeout-minutes: 90
    name: ðŸ§ª Running E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      #
      - name: ðŸ“¦ Install dependencies
        run: npm install
      #  
      - name: ðŸ–¥ï¸ Install Playwright Browsers
        run: npx playwright install
      #  
      - name: ðŸ§¾ Run Playwright tests
        run: npx playwright test
      #    
      - name: ðŸ“œ Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #
      - name: Publish XML report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if tests failed
        with:
          name: Playwright Tests
          path: test-results/junit-results.xml
          reporter: java-junit
          fail-on-error: true
      - name: ðŸ“Š Generate Allure Report with history
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_history: allure-history
          allure_report: allure-report
          keep_reports: 30
        #
      - name: ðŸš€ Publish test report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true
        #  
      - name: Parse JUnit summary
        if: always()
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          total=$(xmllint --xpath "string(/testsuites/@tests)" test-results/junit-results.xml)
          failed=$(xmllint --xpath "string(/testsuites/@failures)" test-results/junit-results.xml)
          skipped=$(xmllint --xpath "string(/testsuites/@skipped)" test-results/junit-results.xml)
          errors=$(xmllint --xpath "string(/testsuites/@errors)" test-results/junit-results.xml)
          passed=$((total - failed - skipped - errors))
      
          echo "TEST_TOTAL=$total" >> $GITHUB_ENV
          echo "TEST_PASSED=$passed" >> $GITHUB_ENV
          echo "TEST_FAILED=$failed" >> $GITHUB_ENV
      
         

      
